import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

export interface PdfExportOptions {
  filename: string
  reportTitle: string
  generatedBy?: string
  dateRange?: string
  appliedFilters?: string
  summaryStats?: { label: string; value: string | number }[]
  columns: { header: string; dataKey: string }[]
  // Rows are heterogeneous domain objects; values are read by key and stringified.
  data: object[]
}

export function exportToPdf({
  filename,
  reportTitle,
  generatedBy = "System Administrator",
  dateRange,
  appliedFilters,
  summaryStats,
  columns,
  data,
}: PdfExportOptions) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  })

  const pageWidth = doc.internal.pageSize.getWidth()

  // Institution Header
  doc.setFont("helvetica", "bold")
  doc.setFontSize(14)
  doc.setTextColor(20, 20, 20)
  doc.text("PANYOR HALL OF RESIDENCE", pageWidth / 2, 16, { align: "center" })

  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(80, 80, 80)
  doc.text("Rajiv Gandhi University (RGU), Rono Hills, Doimukh, Arunachal Pradesh", pageWidth / 2, 22, {
    align: "center",
  })

  // Divider line
  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.4)
  doc.line(14, 26, pageWidth - 14, 26)

  // Report Title
  doc.setFont("helvetica", "bold")
  doc.setFontSize(12)
  doc.setTextColor(30, 30, 30)
  doc.text(reportTitle.toUpperCase(), 14, 34)

  // Metadata block
  doc.setFont("helvetica", "normal")
  doc.setFontSize(8.5)
  doc.setTextColor(90, 90, 90)

  const printTime = new Date().toLocaleString()
  doc.text(`Generated: ${printTime}`, 14, 40)
  doc.text(`Generated By: ${generatedBy}`, 14, 45)

  if (dateRange) {
    doc.text(`Period: ${dateRange}`, pageWidth - 14, 40, { align: "right" })
  }
  if (appliedFilters) {
    doc.text(`Filters: ${appliedFilters}`, pageWidth - 14, 45, { align: "right" })
  }

  let currentY = 52

  // Summary statistics badges/boxes if provided
  if (summaryStats && summaryStats.length > 0) {
    doc.setFillColor(245, 245, 247)
    doc.roundedRect(14, currentY, pageWidth - 28, 14, 2, 2, "F")

    const statWidth = (pageWidth - 28) / summaryStats.length
    summaryStats.forEach((stat, idx) => {
      const x = 14 + idx * statWidth + 4
      doc.setFont("helvetica", "bold")
      doc.setFontSize(9)
      doc.setTextColor(30, 30, 30)
      doc.text(String(stat.value), x, currentY + 6)

      doc.setFont("helvetica", "normal")
      doc.setFontSize(7.5)
      doc.setTextColor(110, 110, 110)
      doc.text(stat.label, x, currentY + 11)
    })

    currentY += 18
  }

  // Data Table
  const tableRows = data.map((item) => {
    const source = item as Record<string, unknown>
    return columns.map((c) => {
      const cell = source[c.dataKey]
      return cell !== undefined && cell !== null ? String(cell) : "-"
    })
  })

  autoTable(doc, {
    startY: currentY,
    head: [columns.map((c) => c.header)],
    body: tableRows,
    theme: "striped",
    headStyles: {
      fillColor: [30, 30, 30],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8.5,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [40, 40, 40],
    },
    alternateRowStyles: {
      fillColor: [248, 248, 250],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (pageData) => {
      // Footer page numbering
      const totalPages = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages()
      doc.setFontSize(7.5)
      doc.setTextColor(140, 140, 140)
      doc.text(
        `Panyor Hall of Residence Management System • Page ${pageData.pageNumber} of ${totalPages}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 8,
        { align: "center" }
      )
    },
  })

  doc.save(`${filename}.pdf`)
}
